<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Authors>DolphinWing</Authors>
    <Copyright>Copyright @ 2026</Copyright>
    <Description>ONI Font Loader. rebuilt by DolphinWing.</Description>
    
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    
    <AssemblyTitle>FontLoader</AssemblyTitle>
    <Version>2.2.0</Version>
    <FileVersion>2026.03.13.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PLib" Version="4.19.0" /> 
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony" HintPath="lib\0Harmony.dll" Private="True" />
    <Reference Include="Assembly-CSharp" HintPath="lib\Assembly-CSharp.dll" Private="True" />
    <Reference Include="Assembly-CSharp-firstpass" HintPath="lib\Assembly-CSharp-firstpass.dll" Private="True" />
    <Reference Include="UnityEngine" HintPath="lib\UnityEngine.dll" Private="True" />
    <Reference Include="UnityEngine.AssetBundleModule" HintPath="lib\UnityEngine.AssetBundleModule.dll" Private="True" />
    <Reference Include="UnityEngine.CoreModule" HintPath="lib\UnityEngine.CoreModule.dll" Private="True" />
    <Reference Include="UnityEngine.TextCoreFontEngineModule">
      <HintPath>lib\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI" HintPath="lib\UnityEngine.UI.dll" Private="True" />
    <Reference Include="Unity.TextMeshPro" HintPath="lib\Unity.TextMeshPro.dll" Private="True" />
    <Reference Include="Newtonsoft.Json">
      <HintPath>lib\Newtonsoft.Json.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

</Project>