<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Authors>DolphinWing</Authors>
    <Copyright>Copyright @ 2026</Copyright>
    <Description>ONI Font Loader. rebuilt by DolphinWing.</Description>
    
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    
    <AssemblyTitle>FontLoader</AssemblyTitle>
    <Version>2.3.0</Version>
    <FileVersion>2026.721.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" /> 
  </ItemGroup>

  <ItemGroup>
    <!--<Reference Include="0Harmony" HintPath="..\OniManagedLibs\0Harmony.dll" Private="False" />-->
    <Reference Include="Assembly-CSharp" HintPath="..\OniManagedLibs\Assembly-CSharp.dll" Private="False" />
    <Reference Include="Assembly-CSharp-firstpass" HintPath="..\OniManagedLibs\Assembly-CSharp-firstpass.dll" Private="False" />
    <Reference Include="UnityEngine" HintPath="..\OniManagedLibs\UnityEngine.dll" Private="False" />
    <Reference Include="UnityEngine.AssetBundleModule" HintPath="..\OniManagedLibs\UnityEngine.AssetBundleModule.dll" Private="False" />
    <Reference Include="UnityEngine.CoreModule" HintPath="..\OniManagedLibs\UnityEngine.CoreModule.dll" Private="False" />
    <Reference Include="UnityEngine.TextCoreFontEngineModule">
      <HintPath>..\OniManagedLibs\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
	  <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI" HintPath="..\OniManagedLibs\UnityEngine.UI.dll" Private="False" />
    <Reference Include="Unity.TextMeshPro" HintPath="..\OniManagedLibs\Unity.TextMeshPro.dll" Private="False" />
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\OniManagedLibs\Newtonsoft.Json.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

</Project>
