<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>Rime_Extreme_2</AssemblyName>
    <RootNamespace>NotZeroK</RootNamespace>
    <Authors>DolphinWing</Authors>
    <Version>2.0.0</Version>
    
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony" HintPath="lib\0Harmony.dll" Private="True" />
    <Reference Include="Assembly-CSharp" HintPath="lib\Assembly-CSharp.dll" Private="True" />
    <Reference Include="Assembly-CSharp-firstpass" HintPath="lib\Assembly-CSharp-firstpass.dll" Private="True" />
    <Reference Include="Newtonsoft.Json" HintPath="lib\Newtonsoft.Json.dll" Private="True" />
    <Reference Include="UnityEngine" HintPath="lib\UnityEngine.dll" Private="True" />
    <Reference Include="UnityEngine.CoreModule" HintPath="lib\UnityEngine.CoreModule.dll" Private="True" />
    <Reference Include="UnityEngine.UI" HintPath="lib\UnityEngine.UI.dll" Private="True" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PLib" Version="4.19.0" />
    <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.44.1" /> 
  </ItemGroup>

</Project>