<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AssemblyName>TorchGod_Heliconia</AssemblyName>
    <Authors>DolphinWing</Authors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Properties\AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony" HintPath="lib\0Harmony.dll" Private="False" />
    <Reference Include="Assembly-CSharp" HintPath="lib\Assembly-CSharp.dll" Private="False" />
    <Reference Include="Assembly-CSharp-firstpass" HintPath="lib\Assembly-CSharp-firstpass.dll" Private="False" />
    <Reference Include="Newtonsoft.Json" HintPath="lib\Newtonsoft.Json.dll" Private="False" />
    <Reference Include="UnityEngine" HintPath="lib\UnityEngine.dll" Private="False" />
    <Reference Include="UnityEngine.CoreModule" HintPath="lib\UnityEngine.CoreModule.dll" Private="False" />
    <Reference Include="UnityEngine.UI" HintPath="lib\UnityEngine.UI.dll" Private="False" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.44.1" />
    <PackageReference Include="PLib" Version="4.19.0" />
  </ItemGroup>
</Project>